In [202]:
import pandas as pd

#### Load the datasets

In [203]:
patients =pd.read_csv("../data/raw_data/patients.csv")
appointments = pd.read_csv("../data/raw_data/appointments.csv")
doctors = pd.read_csv("../data/raw_data/doctors.csv")
billing = pd.read_csv("../data/raw_data/billing.csv")

### Exploring The Patients Dataset

#### patients.head() is to show the first few rows of a dataframe os that you can quickly peek at your data without printing the whole thing.

In [204]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,0808-783-0713,not_an_email,Kano,24/04/2023
1,P00162,Grace Ogunleye,NaN,25,0802 815 3780,NaN,Benin city,"Aug 28, 2024"
2,P00986,David Garba,NaN,15,NaN,david.garba474@email.com,Lagos,2024/09/06
3,P00503,GRACE NWOSU,female,-5,0809-542-1859,NaN,ABUJA,2022-08-24
4,P00463,Tolu Ojo,NaN,NaN,0800-757-8203,tolu.ojo372@email.com,Benin city,26/04/2026
...,...,...,...,...,...,...,...,...
1665,P01559,Grace Balogun,female,46,8053985671,grace.balogun38@yahoo.com,IBADAN,2024-10-08
1666,P01184,Amaka Sani,Female,28,+2348010265670,AMAKA.SANI916@GMAIL.COM,lagos,2022/09/09
1667,P00494,Tunde Usman,female,Thirty-Five,0804 029 4698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,female,Thirty-Five,08077024790,hannah.johnson285@yahoo.com,ibadan,2024-05-15
1669,P01193,John Afolabi,NaN,NaN,+2348071099450,john.afolabi498@email.com,Abuja,2022-07-31

### patients.tail() it shows you the last few rows of a dataframe

In [205]:
patients.tail()

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
1665,P01559,Grace Balogun,female,46,8053985671,grace.balogun38@yahoo.com,IBADAN,2024-10-08
1666,P01184,Amaka Sani,Female,28,+2348010265670,AMAKA.SANI916@GMAIL.COM,lagos,2022/09/09
1667,P00494,Tunde Usman,female,Thirty-Five,0804 029 4698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,female,Thirty-Five,08077024790,hannah.johnson285@yahoo.com,ibadan,2024-05-15
1669,P01193,John Afolabi,NaN,NaN,+2348071099450,john.afolabi498@email.com,Abuja,2022-07-31

### Patients.info() gives you quick overview of a dataframe's structure

In [206]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 1670 entries, 0 to 1669
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         1633 non-null   str
 1   full_name          1670 non-null   str
 2   gender             1241 non-null   str
 3   age                1083 non-null   str
 4   phone_number       1525 non-null   str
 5   email              1211 non-null   str
 6   city               1670 non-null   str
 7   registration_date  1670 non-null   str
dtypes: str(8)
memory usage: 104.5 KB

In [207]:
patients.shape

(1670, 8)

### patients.describe() gives you a quick statistical summary of your data- mean, min. max- all in a one shot

In [208]:
patients.describe()

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
count,1633,1670,1241,1083,1525,1211,1670,1670
unique,1566,562,6,92,1313,1037,18,1479
top,P01434,Ngozi Eze,M,-5,12345,not_an_email,Kano,30/07/2026
freq,2,12,226,283,79,115,118,4

### .duplicated() tells you how many duplicate rows exist in your Dataframe

In [209]:
patients.duplicated().sum()

np.int64(70)

In [210]:
patients = patients.drop_duplicates()

In [211]:
patients.duplicated().sum()

np.int64(0)

### .isnull() gives you how many missing values exist in each column of your dataframe

In [212]:
patients.isnull().sum()

patient_id            34
full_name              0
gender               413
age                  559
phone_number         140
email                445
city                   0
registration_date      0
dtype: int64

### Standardizing The City Column

In [213]:
patients["city"].unique()

<StringArray>
[         'Kano',    'Benin city',         'Lagos',         'ABUJA',
         'enugu',        'ibadan', 'PORT HARCOURT', 'Port Harcourt',
         'lagos',        'IBADAN',         'abuja',         'Abuja',
 'port harcourt',         'LAGOS',          'kano',        'Ibadan',
         'LaGoS',         'ENUGU']
Length: 18, dtype: str

In [214]:
patients["city"] = patients["city"].str.title()

In [215]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,0808-783-0713,not_an_email,Kano,24/04/2023
1,P00162,Grace Ogunleye,NaN,25,0802 815 3780,NaN,Benin City,"Aug 28, 2024"
2,P00986,David Garba,NaN,15,NaN,david.garba474@email.com,Lagos,2024/09/06
3,P00503,GRACE NWOSU,female,-5,0809-542-1859,NaN,Abuja,2022-08-24
4,P00463,Tolu Ojo,NaN,NaN,0800-757-8203,tolu.ojo372@email.com,Benin City,26/04/2026
...,...,...,...,...,...,...,...,...
1664,P00300,Michael Johnson,Male,Thirty-Five,0808 083 0429,michael.johnson_email.com,Lagos,2024-10-07
1665,P01559,Grace Balogun,female,46,8053985671,grace.balogun38@yahoo.com,Ibadan,2024-10-08
1667,P00494,Tunde Usman,female,Thirty-Five,0804 029 4698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,female,Thirty-Five,08077024790,hannah.johnson285@yahoo.com,Ibadan,2024-05-15
1669,P01193,John Afolabi,NaN,NaN,+2348071099450,john.afolabi498@email.com,Abuja,2022-07-31

In [216]:
patients["city"].unique()

<StringArray>
['Kano', 'Benin City', 'Lagos', 'Abuja', 'Enugu', 'Ibadan', 'Port Harcourt']
Length: 7, dtype: str

### Clean the gender column

#### .unque() returns all the distinct values in a column, with duplicate removed

In [217]:
patients["gender"].unique()

<StringArray>
['M', nan, 'female', 'Female', 'male', 'Male', 'F']
Length: 7, dtype: str

In [218]:
# standardize the gender column
patients["gender"] = patients["gender"].replace({"m" : "male", "female" : "Female", "F" : "Female", "male" : "Male"})

In [219]:
patients["gender"].unique()

<StringArray>
['M', nan, 'Female', 'Male']
Length: 4, dtype: str

In [220]:
# filling the missing value
patients["gender"] = patients["gender"].fillna("unkown")

In [221]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,0808-783-0713,not_an_email,Kano,24/04/2023
1,P00162,Grace Ogunleye,unkown,25,0802 815 3780,NaN,Benin City,"Aug 28, 2024"
2,P00986,David Garba,unkown,15,NaN,david.garba474@email.com,Lagos,2024/09/06
3,P00503,GRACE NWOSU,Female,-5,0809-542-1859,NaN,Abuja,2022-08-24
4,P00463,Tolu Ojo,unkown,NaN,0800-757-8203,tolu.ojo372@email.com,Benin City,26/04/2026
...,...,...,...,...,...,...,...,...
1664,P00300,Michael Johnson,Male,Thirty-Five,0808 083 0429,michael.johnson_email.com,Lagos,2024-10-07
1665,P01559,Grace Balogun,Female,46,8053985671,grace.balogun38@yahoo.com,Ibadan,2024-10-08
1667,P00494,Tunde Usman,Female,Thirty-Five,0804 029 4698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,Female,Thirty-Five,08077024790,hannah.johnson285@yahoo.com,Ibadan,2024-05-15
1669,P01193,John Afolabi,unkown,NaN,+2348071099450,john.afolabi498@email.com,Abuja,2022-07-31

#### Clean Emails column

In [222]:
# Finding the missing value
patients["email"].isnull().sum()

np.int64(445)

In [223]:
patients.info()

<class 'pandas.DataFrame'>
Index: 1600 entries, 0 to 1669
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         1566 non-null   str
 1   full_name          1600 non-null   str
 2   gender             1600 non-null   str
 3   age                1041 non-null   str
 4   phone_number       1460 non-null   str
 5   email              1155 non-null   str
 6   city               1600 non-null   str
 7   registration_date  1600 non-null   str
dtypes: str(8)
memory usage: 112.5 KB

In [224]:
patients["email"]

0                        not_an_email
1                                 NaN
2            david.garba474@email.com
3                                 NaN
4               tolu.ojo372@email.com
                    ...
1664        michael.johnson_email.com
1665       grace.balogun38@yahoo.com
1667          tunde.usman30@email.com
1668     hannah.johnson285@yahoo.com
1669        john.afolabi498@email.com
Name: email, Length: 1600, dtype: str

In [225]:
# Replacing missing emails with a placeholder value
patients["email"] = patients["email"].fillna("Not Provided")

### Clean Age

In [226]:
patients["age"]

0                12
1                25
2                15
3                -5
4               NaN
           ...
1664    Thirty-Five
1665             46
1667    Thirty-Five
1668    Thirty-Five
1669            NaN
Name: age, Length: 1600, dtype: str

### Converting the age value to integer/numeric

In [227]:
patients["age"] = pd.to_numeric(patients["age"], errors = "coerce") #Replace anything that cannot be converted to a number with NaN(Not a Number). Invalid age become NaN

In [228]:
#Replace missing age values
patients["age"] = patients["age"].fillna(
    patients["age"].median()
    )

In [229]:
patients["age"]  # Here, we are still getting float value and negative values. we will convert the age values to integer and replace negative valiue with the median value.

0       12.0
1       25.0
2       15.0
3       -5.0
4       23.0
        ...
1664    23.0
1665    46.0
1667    23.0
1668    23.0
1669    23.0
Name: age, Length: 1600, dtype: float64

In [230]:
# Replace negative ages with missing  values
patients.loc[patients["age"]< 0, "age"] = pd.NA  # what this line of code does is that it replace any negative age values with amissing value (NaN). This is done because negative age are not valid and should be treated as missing date. By replacing them with NaN, we can then handle them appropriately, such as filling them with the median age value later on.

# Fill missing with the median()
patients["age"] = patients["age"].fillna(patients["age"].median())


# Round age
patients["age"] = patients["age"].round()

# convert to integers
patients["age"] = patients["age"].astype(int)

In [231]:
# verify the cleaning of the age column
# check for negative values
patients[patients["age"] < 0]

Empty DataFrame
Columns: [patient_id, full_name, gender, age, phone_number, email, city, registration_date]
Index: []

In [232]:
# Check for decimals 
patients["age"].dtype

dtype('int64')

In [233]:
patients["age"]

0       12
1       25
2       15
3       23
4       23
        ..
1664    23
1665    46
1667    23
1668    23
1669    23
Name: age, Length: 1600, dtype: int64

In [234]:
patients["patient_id"]

0       P01600
1       P00162
2       P00986
3       P00503
4       P00463
         ...
1664    P00300
1665    P01559
1667    P00494
1668    P00528
1669    P01193
Name: patient_id, Length: 1600, dtype: str

#### Fixing the missing in the patient_id Column

In [235]:
# Checking the number of missing values in the patient_id column 
#patients["patient_id"].isnull().sum()
patients["patient_id"].isna().sum()

np.int64(34)

In [236]:
# View the affected rows  
patients[patients["patient_id"].isna()]

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
13,NaN,Aisha Adeyemi,unkown,23,08008586726,AISHA.ADEYEMI883@GMAIL.COM,Abuja,2021/01/22
24,NaN,Mercy Adeyemi,Female,23,+2348036868737,Not Provided,Lagos,2021-05-06
29,NaN,Mary Okafor,Male,84,08027195834,MARY.OKAFOR658@GMAIL.COM,Lagos,2022/08/02
38,NaN,Ngozi Adewale,Female,23,+2348058101038,NGOZI.ADEWALE635@GMAIL.COM,Lagos,"Feb 19, 2024"
51,NaN,Kemi Balogun,unkown,23,08078616134,Not Provided,Kano,2024-09-30
82,NaN,Emeka Eze,Female,55,0805-792-1922,emeka.eze_email.com,Kano,2024/09/27
174,NaN,Michael Ibrahim,Male,81,0801-823-7489,michael.ibrahim81@yahoo.com,Ibadan,2026/10/26
271,NaN,Abdul Ojo,Female,14,8089763062,ABDUL.OJO411@GMAIL.COM,Lagos,"Sep 15, 2026"
297,NaN,David Usman,Male,23,NaN,Not Provided,Abuja,19/12/2021
318,NaN,Emeka Adeyemi,M,23,NaN,EMEKA.ADEYEMI903@GMAIL.COM,Port Harcourt,2021-12-12
475,NaN,Tunde Nwosu,Male,23,08020457778,Not Provided,Benin City,2025-04-11
529,NaN,Tunde Onyeka,Female,44,0803 711 2906,TUNDE.ONYEKA296@GMAIL.COM,Abuja,20/09/2023
543,NaN,Esther Onyeka,Male,23,+2348001533666,esther.onyeka24@yahoo.com,Abuja,"Jan 21, 2022"
600,NaN,Chinedu Ogunleye,unkown,23,0805-615-6010,Not Provided,Ibadan,13/03/2023
682,NaN,Peter Usman,Male,23,+2348039674772,peter.usman47@yahoo.com,Abuja,19/12/2023
782,NaN,Blessing Ojo,unkown,34,8023968046,blessing.ojo365@email.com,Lagos,"Mar 01, 2026"
849,NaN,Blessing Onyeka,unkown,82,0808-749-8242,not_an_email,Benin City,"Aug 22, 2021"
864,NaN,Mary Nwosu,unkown,23,08002140353,not_an_email,Port Harcourt,2023-06-06
910,NaN,Zainab Afolabi,Male,23,8027507041,ZAINAB.AFOLABI529@GMAIL.COM,Lagos,"Jun 15, 2022"
914,NaN,Aisha Okafor,Female,78,0809 217 9830,AISHA.OKAFOR793@GMAIL.COM,Lagos,"Nov 26, 2026"
934,NaN,Esther Chukwu,unkown,23,0804-176-0836,ESTHER.CHUKWU798@GMAIL.COM,Lagos,08/08/2023
936,NaN,Ada Balogun,unkown,23,08087513866,Not Provided,Abuja,2024-09-18
976,NaN,Musa Balogun,Female,23,08031952625,Not Provided,Port Harcourt,2023/12/26
1033,NaN,Bola Johnson,Male,23,0802-196-4721,Not Provided,Kano,2021-09-15
1050,NaN,Mercy Ibrahim,Male,9,0805 647 6225,Not Provided,Ibadan,03/07/2026
1104,NaN,Kemi Adeyemi,Female,23,8056592357,kemi.adeyemi391@email.com,Port Harcourt,15/03/2026
1154,NaN,Chinedu Abubakar,M,23,0809 571 8137,chinedu.abubakar17@yahoo.com,Abuja,2023-12-23
1192,NaN,Samuel Usman,M,23,8060283964,samuel.usman471@yahoo.com,Port Harcourt,06-13-2023
1226,NaN,Michael Ogunleye,Female,1,0807 794 5605,michael.ogunleye125@email.com,Port Harcourt,05-03-2022
1368,NaN,Michael Abubakar,Male,23,0804 705 8115,MICHAEL.ABUBAKAR752@GMAIL.COM,Ibadan,2025/03/30
1425,NaN,Tunde Uche,M,31,08089363170,not_an_email,Benin City,2022/02/18
1501,NaN,Grace Johnson,unkown,42,08079370660,Not Provided,Port Harcourt,10-17-2022
1556,NaN,Tolu Ojo,Female,22,0800-181-1477,tolu.ojo_email.com,Port Harcourt,"Feb 05, 2021"
1647,NaN,Ibrahim Afolabi,unkown,23,+2348007402024,ibrahim.afolabi596@email.com,Ibadan,17/09/2026

In [237]:
# Find missing IDs
missing_rows = patients[patients["patient_id"].isna()].index

# Generate new IDs
for i, idx in enumerate(missing_rows, start=1601):
    patients.loc[idx, "patient_id"] = f"P{i:05d}"

In [238]:
# Verify 
patients["patient_id"].isna().sum()

np.int64(0)

In [239]:
# Check for duplicates in the patient_id column
patients["patient_id"].duplicated().sum()

np.int64(0)

In [240]:
# checking for any remaining missing values in the patient_id column
patients[patients["patient_id"].isna()]

Empty DataFrame
Columns: [patient_id, full_name, gender, age, phone_number, email, city, registration_date]
Index: []

#### Standardizing the format of the full_name column

In [241]:
# Standardize names to Title Case
patients["full_name"] = patients["full_name"].str.title()

In [242]:
patients["full_name"]

0            Mary Nwosu
1        Grace Ogunleye
2           David Garba
3           Grace Nwosu
4              Tolu Ojo
             ...
1664    Michael Johnson
1665      Grace Balogun
1667        Tunde Usman
1668     Hannah Johnson
1669       John Afolabi
Name: full_name, Length: 1600, dtype: str

In [243]:
#patients["full_name"].head(10) # This displays the first 10 names in the full_name column
patients["full_name"].sample(10) # This displays a random sample of 10 names in the full_name column

885           Mary Garba
576          Chinedu Ojo
1636           Emeka Eze
1003          Mercy Musa
1241      Grace Ogunleye
440          Tolu Onyeka
454         Victor Garba
724        Peter Johnson
96        Esther Afolabi
971     Blessing Ibrahim
Name: full_name, dtype: str

#### Clean the phone_number column

In [244]:
# Always inspect your data before and after cleaning
# Before cleaning, let's check the phone_number column for any inconsistencies or missing values

patients["phone_number"]

0        0808-783-0713
1        0802 815 3780
2                  NaN
3        0809-542-1859
4        0800-757-8203
             ...
1664     0808 083 0429
1665        8053985671
1667     0804 029 4698
1668       08077024790
1669    +2348071099450
Name: phone_number, Length: 1600, dtype: str

In [245]:
# Dealing with the missing values in the phone_number column first 
# Check for missing values in the phone_number column
patients["phone_number"].isna().sum()

np.int64(140)

In [246]:
# Fill the missing values in the phone_number column with "Unknown"
patients["phone_number"] = patients["phone_number"].fillna("Unknown")

In [247]:
# checking for any remaining missing values in the patient_id column
patients[patients["patient_id"].isna()]

Empty DataFrame
Columns: [patient_id, full_name, gender, age, phone_number, email, city, registration_date]
Index: []

#### Remove spaces in the phone_number column

In [248]:
patients["phone_number"] = patients["phone_number"].str.replace(" ", "", regex=False) # this means that any spaces in the phone_number column will be removed. The regex=False argument indicates that we are not using regular expressions for this replacement, but rather a simple string replacement. This is done to ensure that the phone numbers are in a consistent format without any spaces.

#### Remove Hyphens in the phone_number column

In [249]:
patients["phone_number"] = patients["phone_number"].str.replace(" ", "", regex=False) # this means that any spaces in the phone_number column will be removed. The regex=False argument indicates that we are not using regular expressions for this replacement, but rather a simple string replacement. This is done to ensure that the phone numbers are in a consistent format without any spaces.

#### Convert +234 numbers to Nigerian format

In [250]:
patients["phone_number"] = patients["phone_number"].str.replace(
    r"^\+234",
    "0",
    regex=True
)

In [251]:
patients["phone_number"]

0       0808-783-0713
1         08028153780
2             Unknown
3       0809-542-1859
4       0800-757-8203
            ...
1664      08080830429
1665       8053985671
1667      08040294698
1668      08077024790
1669      08071099450
Name: phone_number, Length: 1600, dtype: str

### Addding the missing leading zero

In [252]:
patients["phone_number"] = patients["phone_number"].apply(
    lambda x: "0" + x
    if isinstance(x, str) and x.isdigit() and len(x) == 10
    else x
)

In [253]:
patients["phone_number"]

0       0808-783-0713
1         08028153780
2             Unknown
3       0809-542-1859
4       0800-757-8203
            ...
1664      08080830429
1665      08053985671
1667      08040294698
1668      08077024790
1669      08071099450
Name: phone_number, Length: 1600, dtype: str

In [254]:
patients["phone_number"] = patients["phone_number"].replace({
    "not_available": "Unknown"
})

In [255]:
patients["phone_number"]

0       0808-783-0713
1         08028153780
2             Unknown
3       0809-542-1859
4       0800-757-8203
            ...
1664      08080830429
1665      08053985671
1667      08040294698
1668      08077024790
1669      08071099450
Name: phone_number, Length: 1600, dtype: str

In [256]:
# Replace invalid phone numbers
# A Nigerian phone number should contain 11 digits.
#Anything shorter or longer is invalid. 

patients["phone_number"] = patients["phone_number"].apply(
    lambda x: "Unknown"
    if isinstance(x, str)
    and x != "Unknown"
    and (not x.isdigit() or len(x) != 11)
    else x
)

"""
This will automatically convert:
12345 into Unknown

while leaving 08026951234 unchanged.
"""

'\nThis will automatically convert:\n12345 into Unknown\n\nwhile leaving 08026951234 unchanged.\n'

In [257]:
patients["phone_number"]

0           Unknown
1       08028153780
2           Unknown
3           Unknown
4           Unknown
           ...
1664    08080830429
1665    08053985671
1667    08040294698
1668    08077024790
1669    08071099450
Name: phone_number, Length: 1600, dtype: str

In [258]:
# Display a sample of 20 phone numbers to verify the cleaning process
patients["phone_number"].sample(20)

675     08074810538
936     08087513866
1663        Unknown
1264    08020674245
693     08054139822
963         Unknown
503     08080151159
211     08043369748
838     08017403908
240     08053596414
1207    08072222883
469     08028137066
185     08039538446
1183    08002269276
255     08021662330
685     08054752350
849         Unknown
420     08029869655
393         Unknown
197     08014951097
Name: phone_number, dtype: str

In [259]:
patients["email"]

0                        not_an_email
1                        Not Provided
2            david.garba474@email.com
3                        Not Provided
4               tolu.ojo372@email.com
                    ...
1664        michael.johnson_email.com
1665       grace.balogun38@yahoo.com
1667          tunde.usman30@email.com
1668     hannah.johnson285@yahoo.com
1669        john.afolabi498@email.com
Name: email, Length: 1600, dtype: str

### convert all emails to lowercase. Emails are case-insensitive, so it's best practice to store them in lowercase

In [260]:
patients["email"] = patients["email"].str.lower()

In [261]:
patients["email"] = patients["email"].replace({
    "Not Provided": "Unknown",
    "not_an_email": "Unknown",
    "not provided": "Unknown",
    "not available": "Unknown",
    "n/a": "Unknown",
    "none": "Unknown"
})

In [262]:
patients["email"]

0                             Unknown
1                             Unknown
2            david.garba474@email.com
3                             Unknown
4               tolu.ojo372@email.com
                    ...
1664        michael.johnson_email.com
1665       grace.balogun38@yahoo.com
1667          tunde.usman30@email.com
1668     hannah.johnson285@yahoo.com
1669        john.afolabi498@email.com
Name: email, Length: 1600, dtype: str

#### Identify emails missing '@'

In [263]:
patients["email"] = patients["email"].apply(
    lambda x: "Unknown"
    if x != "Unknown" and "@" not in x
    else x
)
#Instead of automatically fixing them (which may introduce incorrect data), mark them as unknown.

In [264]:
# Count the unknown values
patients["email"].value_counts().head(10)

email
Unknown                        662
david.garba474@email.com         1
tolu.ojo372@email.com            1
tolu.balogun627@email.com        1
 ibrahim.sani167@yahoo.com       1
zainab.balogun644@email.com      1
 zainab.bello276@yahoo.com       1
zainab.eze498@email.com          1
aisha.adeyemi883@gmail.com       1
 kemi.uche711@yahoo.com          1
Name: count, dtype: int64

### Data Transformation

In [265]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,Unknown,Unknown,Kano,24/04/2023
1,P00162,Grace Ogunleye,unkown,25,08028153780,Unknown,Benin City,"Aug 28, 2024"
2,P00986,David Garba,unkown,15,Unknown,david.garba474@email.com,Lagos,2024/09/06
3,P00503,Grace Nwosu,Female,23,Unknown,Unknown,Abuja,2022-08-24
4,P00463,Tolu Ojo,unkown,23,Unknown,tolu.ojo372@email.com,Benin City,26/04/2026
...,...,...,...,...,...,...,...,...
1664,P00300,Michael Johnson,Male,23,08080830429,Unknown,Lagos,2024-10-07
1665,P01559,Grace Balogun,Female,46,08053985671,grace.balogun38@yahoo.com,Ibadan,2024-10-08
1667,P00494,Tunde Usman,Female,23,08040294698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,Female,23,08077024790,hannah.johnson285@yahoo.com,Ibadan,2024-05-15
1669,P01193,John Afolabi,unkown,23,08071099450,john.afolabi498@email.com,Abuja,2022-07-31

In [266]:
# Current Date 
patients["registration_date"]

0         24/04/2023
1       Aug 28, 2024
2         2024/09/06
3         2022-08-24
4         26/04/2026
            ...
1664      2024-10-07
1665      2024-10-08
1667      2021-07-15
1668      2024-05-15
1669      2022-07-31
Name: registration_date, Length: 1600, dtype: str

In [267]:
# Convert registration_date to date only
patients["registration_date"] = (
    pd.to_datetime(
        patients["registration_date"],
        format="%Y/%m/%d",
        errors="coerce"
    )
    .dt.date
)

In [268]:
patients["registration_date"] = patients["registration_date"].fillna("unknown")

In [269]:
patients["registration_date"]

0          unknown
1          unknown
2       2024-09-06
3          unknown
4          unknown
           ...
1664       unknown
1665       unknown
1667       unknown
1668       unknown
1669       unknown
Name: registration_date, Length: 1600, dtype: object

In [270]:
patients["registration_date"].dtype

dtype('O')

In [271]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,Unknown,Unknown,Kano,unknown
1,P00162,Grace Ogunleye,unkown,25,08028153780,Unknown,Benin City,unknown
2,P00986,David Garba,unkown,15,Unknown,david.garba474@email.com,Lagos,2024-09-06
3,P00503,Grace Nwosu,Female,23,Unknown,Unknown,Abuja,unknown
4,P00463,Tolu Ojo,unkown,23,Unknown,tolu.ojo372@email.com,Benin City,unknown
...,...,...,...,...,...,...,...,...
1664,P00300,Michael Johnson,Male,23,08080830429,Unknown,Lagos,unknown
1665,P01559,Grace Balogun,Female,46,08053985671,grace.balogun38@yahoo.com,Ibadan,unknown
1667,P00494,Tunde Usman,Female,23,08040294698,tunde.usman30@email.com,Port Harcourt,unknown
1668,P00528,Hannah Johnson,Female,23,08077024790,hannah.johnson285@yahoo.com,Ibadan,unknown
1669,P01193,John Afolabi,unkown,23,08071099450,john.afolabi498@email.com,Abuja,unknown

### Feature Engineering. Creating New Column

In [272]:
# Creating the Age group column 
patients["age_group"] = pd.cut(
    patients["age"],
    bins=[0,17,35,60,100],
    labels=[
        "Child",
        "Young Adult",
        "Adult",
        "Senior"
    ]
)

In [273]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date,age_group
0,P01600,Mary Nwosu,M,12,Unknown,Unknown,Kano,unknown,Child
1,P00162,Grace Ogunleye,unkown,25,08028153780,Unknown,Benin City,unknown,Young Adult
2,P00986,David Garba,unkown,15,Unknown,david.garba474@email.com,Lagos,2024-09-06,Child
3,P00503,Grace Nwosu,Female,23,Unknown,Unknown,Abuja,unknown,Young Adult
4,P00463,Tolu Ojo,unkown,23,Unknown,tolu.ojo372@email.com,Benin City,unknown,Young Adult
...,...,...,...,...,...,...,...,...,...
1664,P00300,Michael Johnson,Male,23,08080830429,Unknown,Lagos,unknown,Young Adult
1665,P01559,Grace Balogun,Female,46,08053985671,grace.balogun38@yahoo.com,Ibadan,unknown,Adult
1667,P00494,Tunde Usman,Female,23,08040294698,tunde.usman30@email.com,Port Harcourt,unknown,Young Adult
1668,P00528,Hannah Johnson,Female,23,08077024790,hannah.johnson285@yahoo.com,Ibadan,unknown,Young Adult
1669,P01193,John Afolabi,unkown,23,08071099450,john.afolabi498@email.com,Abuja,unknown,Young Adult

### Clean Appointment Dataset

In [274]:
# Check out the dataset 
appointments.info()

<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   appointment_id      1778 non-null   str
 1   patient_id          1799 non-null   str
 2   doctor_id           1793 non-null   str
 3   appointment_date    1800 non-null   str
 4   appointment_status  1455 non-null   str
 5   reason_for_visit    1337 non-null   str
dtypes: str(6)
memory usage: 84.5 KB

In [275]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024/09/02,NaN,Consultation
1,A000002,P00374,D1421,2026/04/18,cancelled,Follow-up
2,A000003,P01442,D1125,01-10-2024,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,"Aug 22, 2025",cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024/11/24,completed,Routine Checkup
1796,A001797,P01321,D0460,"May 24, 2025",completed,Diagnosis
1797,A001798,P00919,D0765,06-09-2026,NaN,NaN
1798,A001799,P00716,NaN,21/08/2024,NaN,Consultation
1799,A001800,P00622,D0437,2025/02/26,No Show,NaN

In [276]:
appointments["appointment_id"].isnull().sum()

np.int64(22)

In [277]:
appointments["appointment_id"]

0       A000001
1       A000002
2       A000003
3       A000004
4       A000005
         ...
1795    A001796
1796    A001797
1797    A001798
1798    A001799
1799    A001800
Name: appointment_id, Length: 1800, dtype: str

##### Clean the appointment_id missing rows/values

Since appointmnent_id is the primary key of the appointmnent table, you should not fill missing values with "Unknown" or leave them blank.


A primary key must satisfy three rules:



.   Unique

.   Not Null

.   Stable (should not chnage)


.

In [278]:
# Find the largest appointment_id
# Get the highest appointment number
max_id = (
    appointments["appointment_id"]
    .dropna()
    .str.replace("A", "", regex=False)
    .astype(int)
    .max()
)

print(max_id)

1800

In [279]:
# Generate new appointment IDs for missing values 
# Find rows with missing IDs
missing_rows = appointments["appointment_id"].isna()

# Create new IDs
new_ids = [
    f"A{num:06d}"
    for num in range(max_id + 1, max_id + 1 + missing_rows.sum())
]

# Assign them
appointments.loc[missing_rows, "appointment_id"] = new_ids

In [280]:
# Verify that there are no more missing IDs
appointments["appointment_id"].isnull().sum()

np.int64(0)

In [281]:
appointments.isnull().sum()

appointment_id          0
patient_id              1
doctor_id               7
appointment_date        0
appointment_status    345
reason_for_visit      463
dtype: int64

#### Dealing with missing values in both the patient_id and doctor_id columns

In [282]:
# Fill missing values in the patient_id column with "UNKNOWN_PATIENT" to ensure that all appointments have a patient ID, even if the original data was missing this information. This helps maintain data integrity and allows for better analysis of appointment records.
appointments["patient_id"] = appointments["patient_id"].fillna("UNKNOWN_PATIENT")

In [283]:
# Fill missing values in doctor_id column with "UNKNOWN_DOCTOR" to ensure that all appointments have a doctor ID, even if the original data was missing this information. This helps maintain data integrity and allows for better analysis of appointment records.
appointments["doctor_id"] = appointments["doctor_id"].fillna("UNKNOWN_DOCTOR")

In [284]:
appointments.isnull().sum()

appointment_id          0
patient_id              0
doctor_id               0
appointment_date        0
appointment_status    345
reason_for_visit      463
dtype: int64

In [285]:
# Standardize the Status columns 
appointments["appointment_status"] = (
    appointments["appointment_status"]
    .str.title()
)

In [286]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024/09/02,NaN,Consultation
1,A000002,P00374,D1421,2026/04/18,Cancelled,Follow-up
2,A000003,P01442,D1125,01-10-2024,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,"Aug 22, 2025",Cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024/11/24,Completed,Routine Checkup
1796,A001797,P01321,D0460,"May 24, 2025",Completed,Diagnosis
1797,A001798,P00919,D0765,06-09-2026,NaN,NaN
1798,A001799,P00716,UNKNOWN_DOCTOR,21/08/2024,NaN,Consultation
1799,A001800,P00622,D0437,2025/02/26,No Show,NaN

In [287]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024/09/02,NaN,Consultation
1,A000002,P00374,D1421,2026/04/18,Cancelled,Follow-up
2,A000003,P01442,D1125,01-10-2024,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,"Aug 22, 2025",Cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024/11/24,Completed,Routine Checkup
1796,A001797,P01321,D0460,"May 24, 2025",Completed,Diagnosis
1797,A001798,P00919,D0765,06-09-2026,NaN,NaN
1798,A001799,P00716,UNKNOWN_DOCTOR,21/08/2024,NaN,Consultation
1799,A001800,P00622,D0437,2025/02/26,No Show,NaN

In [288]:
# Check the missing values in the appointment_status column
appointments["appointment_status"].isnull().sum()

np.int64(345)

In [289]:
# Fill up the 345 missing values in the appointment_status column with "Pending"
appointments["appointment_status"] = appointments["appointment_status"].fillna("Pending")

In [290]:
# Check the missing values in the appointment_status column
appointments["appointment_status"].isnull().sum()

np.int64(0)

In [291]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024/09/02,Pending,Consultation
1,A000002,P00374,D1421,2026/04/18,Cancelled,Follow-up
2,A000003,P01442,D1125,01-10-2024,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,"Aug 22, 2025",Cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024/11/24,Completed,Routine Checkup
1796,A001797,P01321,D0460,"May 24, 2025",Completed,Diagnosis
1797,A001798,P00919,D0765,06-09-2026,Pending,NaN
1798,A001799,P00716,UNKNOWN_DOCTOR,21/08/2024,Pending,Consultation
1799,A001800,P00622,D0437,2025/02/26,No Show,NaN

In [292]:
appointments["appointment_date"]

0         2024/09/02
1         2026/04/18
2         01-10-2024
3         2024-03-20
4       Aug 22, 2025
            ...
1795      2024/11/24
1796    May 24, 2025
1797      06-09-2026
1798      21/08/2024
1799      2025/02/26
Name: appointment_date, Length: 1800, dtype: str

In [293]:
appointments["appointment_date"].dtype # The column is an object type (text/string). We will convert it to a datetime format.

In [294]:
# Convert the appointment_date column to datetime format first
appointments["appointment_date"] = pd.to_datetime(
    appointments["appointment_date"],
    errors="coerce",
    format="mixed"
)

In [295]:
appointments["appointment_date"]

0      2024-09-02
1      2026-04-18
2      2024-01-10
3      2024-03-20
4      2025-08-22
          ...
1795   2024-11-24
1796   2025-05-24
1797   2026-06-09
1798   2024-08-21
1799   2025-02-26
Name: appointment_date, Length: 1800, dtype: datetime64[us]

In [296]:
# Now check the data type of the appointment_date column
appointments["appointment_date"].dtype

dtype('<M8[us]')

In [297]:
# Standardize the format. We do not need to convert the appointment_date column to date only because it is already in the correct format. We will just standardize the format to YYYY-MM-DD.
appointments["appointment_date"] = (
    appointments["appointment_date"]
    .dt.strftime("%Y-%m-%d")
)

In [298]:
appointments["appointment_date"]

0       2024-09-02
1       2026-04-18
2       2024-01-10
3       2024-03-20
4       2025-08-22
           ...
1795    2024-11-24
1796    2025-05-24
1797    2026-06-09
1798    2024-08-21
1799    2025-02-26
Name: appointment_date, Length: 1800, dtype: str

In [299]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024-09-02,Pending,Consultation
1,A000002,P00374,D1421,2026-04-18,Cancelled,Follow-up
2,A000003,P01442,D1125,2024-01-10,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,2025-08-22,Cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024-11-24,Completed,Routine Checkup
1796,A001797,P01321,D0460,2025-05-24,Completed,Diagnosis
1797,A001798,P00919,D0765,2026-06-09,Pending,NaN
1798,A001799,P00716,UNKNOWN_DOCTOR,2024-08-21,Pending,Consultation
1799,A001800,P00622,D0437,2025-02-26,No Show,NaN

### Filling the missing values in the reason_for_visit column with unkown

In [300]:
appointments["reason_for_visit"] = appointments["reason_for_visit"].fillna("Unknown")

In [301]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024-09-02,Pending,Consultation
1,A000002,P00374,D1421,2026-04-18,Cancelled,Follow-up
2,A000003,P01442,D1125,2024-01-10,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,2025-08-22,Cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024-11-24,Completed,Routine Checkup
1796,A001797,P01321,D0460,2025-05-24,Completed,Diagnosis
1797,A001798,P00919,D0765,2026-06-09,Pending,Unknown
1798,A001799,P00716,UNKNOWN_DOCTOR,2024-08-21,Pending,Consultation
1799,A001800,P00622,D0437,2025-02-26,No Show,Unknown

#### Clean Billing Dataset

In [302]:
billing.info()

<class 'pandas.DataFrame'>
RangeIndex: 1700 entries, 0 to 1699
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      1682 non-null   str
 1   patient_id      1697 non-null   str
 2   invoice_date    1700 non-null   str
 3   amount_charged  840 non-null    float64
 4   amount_paid     1058 non-null   float64
 5   payment_method  1340 non-null   str
 6   payment_status  1311 non-null   str
dtypes: float64(2), str(5)
memory usage: 93.1 KB

In [303]:
billing

,invoice_id,patient_id,invoice_date,amount_charged,amount_paid,payment_method,payment_status
0,INV000001,P01082,2024-11-02,NaN,25000.00,NaN,NaN
1,INV000002,P01563,12/10/2024,-1000.00,25000.00,Cash,NaN
2,INV000003,P00900,2025/12/05,41912.36,41912.36,cash,paid
3,INV000004,P00846,2025-09-14,NaN,NaN,Transfer,NaN
4,INV000005,P00042,18/01/2023,NaN,25000.00,CARD,PENDING
...,...,...,...,...,...,...,...
1695,INV001696,P00942,12-01-2026,-1000.00,0.00,Bank Transfer,paid
1696,INV001697,P00058,17/11/2023,-1000.00,0.00,Bank Transfer,Pending
1697,INV001698,P01193,"Dec 15, 2026",NaN,NaN,CARD,NaN
1698,INV001699,P00555,06/01/2026,NaN,0.00,Bank Transfer,Pending
1699,INV001700,P00697,08-14-2026,108932.33,0.00,NaN,Pending

In [304]:
# Checking the data quality issue in the billing dataset
billing.describe(include="all")

,invoice_id,patient_id,invoice_date,amount_charged,amount_paid,payment_method,payment_status
count,1682,1697,1700,840.000000,1058.000000,1340,1311
unique,1682,1031,1511,NaN,NaN,7,7
top,INV000001,P00222,"Jul 20, 2024",NaN,NaN,cash,Pending
freq,1,6,4,NaN,NaN,211,239
mean,NaN,NaN,NaN,79435.555952,39796.377032,NaN,NaN
std,NaN,NaN,NaN,109803.680019,66133.913577,NaN,NaN
min,NaN,NaN,NaN,-1000.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,-1000.000000,0.000000,NaN,NaN
50%,NaN,NaN,NaN,-1000.000000,25000.000000,NaN,NaN
75%,NaN,NaN,NaN,161225.227500,25000.000000,NaN,NaN
max,NaN,NaN,NaN,349746.150000,349746.150000,NaN,NaN

In [305]:
# Counting the null values in the billing dataset
billing.isnull().sum()

invoice_id         18
patient_id          3
invoice_date        0
amount_charged    860
amount_paid       642
payment_method    360
payment_status    389
dtype: int64

In [306]:
billing.duplicated().sum()

np.int64(0)

##### Clean invoice_id column

In [307]:
billing["invoice_id"]

0       INV000001
1       INV000002
2       INV000003
3       INV000004
4       INV000005
          ...
1695    INV001696
1696    INV001697
1697    INV001698
1698    INV001699
1699    INV001700
Name: invoice_id, Length: 1700, dtype: str

In [308]:
# remove rows with missing invoice IDs since they represent the primary key.
billing = billing.dropna(subset=["invoice_id"])

In [309]:
billing["invoice_id"]

0       INV000001
1       INV000002
2       INV000003
3       INV000004
4       INV000005
          ...
1695    INV001696
1696    INV001697
1697    INV001698
1698    INV001699
1699    INV001700
Name: invoice_id, Length: 1682, dtype: str

##### Clean patient_id

In [310]:
billing["patient_id"]

0       P01082
1       P01563
2       P00900
3       P00846
4       P00042
         ...
1695    P00942
1696    P00058
1697    P01193
1698    P00555
1699    P00697
Name: patient_id, Length: 1682, dtype: str

In [311]:
# The patient_id column is a foreign key. Just drop the missing values in the patient_id column since they are not many.
billing = billing.dropna(subset=["patient_id"])

In [312]:
billing.isnull().sum()

invoice_id          0
patient_id          0
invoice_date        0
amount_charged    849
amount_paid       631
payment_method    354
payment_status    387
dtype: int64

#### Standardize invoice_date

In [313]:
billing["invoice_date"] = pd.to_datetime(
    billing["invoice_date"],
    errors="coerce",
    format="mixed"
).dt.strftime("%Y-%m-%d")

In [314]:
billing["invoice_date"]

0       2024-11-02
1       2024-12-10
2       2025-12-05
3       2025-09-14
4       2023-01-18
           ...
1695    2026-12-01
1696    2023-11-17
1697    2026-12-15
1698    2026-06-01
1699    2026-08-14
Name: invoice_date, Length: 1679, dtype: str

##### Clean amount_charged column

Issues 

    .   Missing values
    .   Negative amounts (-1000)

In [315]:
# Convert to Numeric  
billing["amount_charged"] = pd.to_numeric(
    billing["amount_charged"],
    errors="coerce"
)

In [316]:
# Replace negative amounts with missing values
billing.loc[
    billing["amount_charged"] < 0,
    "amount_charged"
] = pd.NA

In [317]:
# Fill missing values with median 
billing["amount_charged"] = billing["amount_charged"].fillna(
    billing["amount_charged"].median()
)

In [318]:
billing["amount_charged"]

0       176447.975
1       176447.975
2        41912.360
3       176447.975
4       176447.975
           ...
1695    176447.975
1696    176447.975
1697    176447.975
1698    176447.975
1699    108932.330
Name: amount_charged, Length: 1679, dtype: float64

In [319]:
# Round the amount_charged to the nearest whole number
billing["amount_charged"] = billing["amount_charged"].round().astype(int)

In [320]:
billing["amount_charged"]

0       176448
1       176448
2        41912
3       176448
4       176448
         ...
1695    176448
1696    176448
1697    176448
1698    176448
1699    108932
Name: amount_charged, Length: 1679, dtype: int64

In [321]:
billing.isnull().sum()

invoice_id          0
patient_id          0
invoice_date        0
amount_charged      0
amount_paid       631
payment_method    354
payment_status    387
dtype: int64

#### Dealing with amount_paid column. It is of float type

In [322]:
billing["amount_paid"].dtype

dtype('float64')

In [323]:
# Convert to numeric first 
billing["amount_paid"] = pd.to_numeric(
    billing["amount_paid"],
    errors="coerce"
)

In [324]:
# replace negative values if any 
billing.loc[
    billing["amount_paid"] < 0,
    "amount_paid"
] = 0

In [325]:
# fill missing values with 0
billing["amount_paid"] = billing["amount_paid"].fillna(0)

In [326]:
billing["amount_paid"]

0       25000.00
1       25000.00
2       41912.36
3           0.00
4       25000.00
          ...
1695        0.00
1696        0.00
1697        0.00
1698        0.00
1699        0.00
Name: amount_paid, Length: 1679, dtype: float64

In [327]:
# Round to nearest whole number
billing["amount_paid"] = billing["amount_paid"].round().astype(int)

In [328]:
billing["amount_paid"]

0       25000
1       25000
2       41912
3           0
4       25000
        ...
1695        0
1696        0
1697        0
1698        0
1699        0
Name: amount_paid, Length: 1679, dtype: int64

In [329]:
billing

,invoice_id,patient_id,invoice_date,amount_charged,amount_paid,payment_method,payment_status
0,INV000001,P01082,2024-11-02,176448,25000,NaN,NaN
1,INV000002,P01563,2024-12-10,176448,25000,Cash,NaN
2,INV000003,P00900,2025-12-05,41912,41912,cash,paid
3,INV000004,P00846,2025-09-14,176448,0,Transfer,NaN
4,INV000005,P00042,2023-01-18,176448,25000,CARD,PENDING
...,...,...,...,...,...,...,...
1695,INV001696,P00942,2026-12-01,176448,0,Bank Transfer,paid
1696,INV001697,P00058,2023-11-17,176448,0,Bank Transfer,Pending
1697,INV001698,P01193,2026-12-15,176448,0,CARD,NaN
1698,INV001699,P00555,2026-06-01,176448,0,Bank Transfer,Pending
1699,INV001700,P00697,2026-08-14,108932,0,NaN,Pending

#### Clean payment_method column

In [330]:
# Convert to title case for the payment_method column 
billing["payment_method"] = (
    billing["payment_method"]
    .str.strip()
    .str.title()
)

In [331]:
billing["payment_method"]

0                 NaN
1                Cash
2                Cash
3            Transfer
4                Card
            ...
1695    Bank Transfer
1696    Bank Transfer
1697             Card
1698    Bank Transfer
1699              NaN
Name: payment_method, Length: 1679, dtype: str

In [332]:
# Replace missing values with unknown 
billing["payment_method"] = billing["payment_method"].fillna("Unknown")

In [333]:
billing["payment_method"]

0             Unknown
1                Cash
2                Cash
3            Transfer
4                Card
            ...
1695    Bank Transfer
1696    Bank Transfer
1697             Card
1698    Bank Transfer
1699          Unknown
Name: payment_method, Length: 1679, dtype: str

In [334]:
billing

,invoice_id,patient_id,invoice_date,amount_charged,amount_paid,payment_method,payment_status
0,INV000001,P01082,2024-11-02,176448,25000,Unknown,NaN
1,INV000002,P01563,2024-12-10,176448,25000,Cash,NaN
2,INV000003,P00900,2025-12-05,41912,41912,Cash,paid
3,INV000004,P00846,2025-09-14,176448,0,Transfer,NaN
4,INV000005,P00042,2023-01-18,176448,25000,Card,PENDING
...,...,...,...,...,...,...,...
1695,INV001696,P00942,2026-12-01,176448,0,Bank Transfer,paid
1696,INV001697,P00058,2023-11-17,176448,0,Bank Transfer,Pending
1697,INV001698,P01193,2026-12-15,176448,0,Card,NaN
1698,INV001699,P00555,2026-06-01,176448,0,Bank Transfer,Pending
1699,INV001700,P00697,2026-08-14,108932,0,Unknown,Pending

In [335]:
billing.isnull().sum()

invoice_id          0
patient_id          0
invoice_date        0
amount_charged      0
amount_paid         0
payment_method      0
payment_status    387
dtype: int64

#### Dealing with the payment_status column

In [336]:
# Convert to title case 
billing["payment_status"] = (
    billing["payment_status"]
    .str.strip()
    .str.title()
)

In [337]:
# Fill missing values 
billing["payment_status"] = billing["payment_status"].fillna("Unknown")

#### Validate business rules. Check if anyone paid more than they were charged

In [338]:
billing[
    billing["amount_paid"] >
    billing["amount_charged"]
]

Empty DataFrame
Columns: [invoice_id, patient_id, invoice_date, amount_charged, amount_paid, payment_method, payment_status]
Index: []

In [339]:
# Check for Zero charges 
billing[
    billing["amount_charged"] == 0
]

Empty DataFrame
Columns: [invoice_id, patient_id, invoice_date, amount_charged, amount_paid, payment_method, payment_status]
Index: []

#### Quality checks on billing dataset

In [340]:
billing.isnull().sum()

invoice_id        0
patient_id        0
invoice_date      0
amount_charged    0
amount_paid       0
payment_method    0
payment_status    0
dtype: int64

In [341]:
billing.info()

<class 'pandas.DataFrame'>
Index: 1679 entries, 0 to 1699
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      1679 non-null   str
 1   patient_id      1679 non-null   str
 2   invoice_date    1679 non-null   str
 3   amount_charged  1679 non-null   int64
 4   amount_paid     1679 non-null   int64
 5   payment_method  1679 non-null   str
 6   payment_status  1679 non-null   str
dtypes: int64(2), str(5)
memory usage: 104.9 KB

In [342]:
billing

,invoice_id,patient_id,invoice_date,amount_charged,amount_paid,payment_method,payment_status
0,INV000001,P01082,2024-11-02,176448,25000,Unknown,Unknown
1,INV000002,P01563,2024-12-10,176448,25000,Cash,Unknown
2,INV000003,P00900,2025-12-05,41912,41912,Cash,Paid
3,INV000004,P00846,2025-09-14,176448,0,Transfer,Unknown
4,INV000005,P00042,2023-01-18,176448,25000,Card,Pending
...,...,...,...,...,...,...,...
1695,INV001696,P00942,2026-12-01,176448,0,Bank Transfer,Paid
1696,INV001697,P00058,2023-11-17,176448,0,Bank Transfer,Pending
1697,INV001698,P01193,2026-12-15,176448,0,Card,Unknown
1698,INV001699,P00555,2026-06-01,176448,0,Bank Transfer,Pending
1699,INV001700,P00697,2026-08-14,108932,0,Unknown,Pending

In [343]:
patients.isnull().sum()

patient_id           0
full_name            0
gender               0
age                  0
phone_number         0
email                0
city                 0
registration_date    0
age_group            0
dtype: int64

In [344]:
appointments.isnull().sum()

appointment_id        0
patient_id            0
doctor_id             0
appointment_date      0
appointment_status    0
reason_for_visit      0
dtype: int64

In [345]:
appointments

,appointment_id,patient_id,doctor_id,appointment_date,appointment_status,reason_for_visit
0,A000001,P00686,D0739,2024-09-02,Pending,Consultation
1,A000002,P00374,D1421,2026-04-18,Cancelled,Follow-up
2,A000003,P01442,D1125,2024-01-10,Completed,Consultation
3,A000004,P01176,D0507,2024-03-20,Scheduled,Emergency
4,A000005,P01172,D0400,2025-08-22,Cancelled,Consultation
...,...,...,...,...,...,...
1795,A001796,P01049,D0494,2024-11-24,Completed,Routine Checkup
1796,A001797,P01321,D0460,2025-05-24,Completed,Diagnosis
1797,A001798,P00919,D0765,2026-06-09,Pending,Unknown
1798,A001799,P00716,UNKNOWN_DOCTOR,2024-08-21,Pending,Consultation
1799,A001800,P00622,D0437,2025-02-26,No Show,Unknown

#### Clean thr doctors dataset

In [346]:
doctors.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   doctor_id    1483 non-null   str
 1   doctor_name  1500 non-null   str
 2   specialty    1320 non-null   str
 3   branch       1209 non-null   str
dtypes: str(4)
memory usage: 47.0 KB

In [347]:
doctors.isnull().sum()

doctor_id       17
doctor_name      0
specialty      180
branch         291
dtype: int64

In [348]:
doctors

     doctor_id         doctor_name           specialty         branch
0        D0001   Dr. Peter Balogun         orthopedics      Kano Care
1        D0002    Dr. Esther Usman          pediatrics  LAGOS CENTRAL
2        D0003      Dr. Ada Okafor         Orthopedics    ABUJA NORTH
3        D0004    Dr. Chinedu Uche  Emergency Medicine    Abuja North
4        D0005    Dr. Ibrahim Sani          Cardiology            NaN
...        ...                 ...                 ...            ...
1495     D1496  Dr. Aisha Ogunleye          cardiology    Ibadan West
1496     D1497       Dr. Ngozi Ojo          Obstetrics            NaN
1497     D1498   Dr. Zainab Onyeka                 NaN            NaN
1498     D1499       Dr. Peter Eze    general medicine            NaN
1499     D1500     Dr. Ada Adeyemi         orthopedics    ABUJA NORTH

[1500 rows x 4 columns]

#### Dealing with doctor_id

In [349]:
# Get the highest existing doctor number
max_id = (
    doctors["doctor_id"]
    .dropna()
    .str.replace("D", "", regex=False)
    .astype(int)
    .max()
)

# Find rows with missing doctor_id
missing_rows = doctors["doctor_id"].isna()

# Generate new doctor IDs
new_ids = [
    f"D{num:04d}"
    for num in range(max_id + 1, max_id + 1 + missing_rows.sum())
]

# Assign the new IDs
doctors.loc[missing_rows, "doctor_id"] = new_ids

#### Clean doctor_name Column

In [350]:
doctors["doctor_name"] = (
    doctors["doctor_name"]
    .str.strip()
    .str.title()
)

#### Clean specialty column

In [351]:
doctors["specialty"] = (
    doctors["specialty"]
    .str.strip()
    .str.title()
)

In [352]:
# Fill the missing values in the specialty with unknown
doctors["specialty"] = doctors["specialty"].fillna("Unknown")

In [353]:
# Verify 
doctors["specialty"].unique()

<StringArray>
[       'Orthopedics',         'Pediatrics', 'Emergency Medicine',
         'Cardiology',            'Unknown',          'Radiology',
          'Neurology',   'General Medicine',        'Dermatology',
    'Family Medicine',         'Obstetrics']
Length: 11, dtype: str

In [354]:
# Verify that there are no more missing doctor IDs
doctors["doctor_id"].isnull().sum()
doctors["doctor_id"].duplicated().sum()

np.int64(0)

#### Clean branch column

In [355]:
# Standardize Capitalization 
doctors["branch"] = (
    doctors["branch"]
    .str.strip()
    .str.title()
)

In [356]:
# Fill Missing Values in the branch column with "Unknown" 
doctors["branch"] = doctors["branch"].fillna("Unknown")

In [357]:
# Verify 
doctors["branch"].unique()

<StringArray>
[         'Kano Care',      'Lagos Central',        'Abuja North',
            'Unknown', 'Port Harcourt Main',        'Ibadan West',
         'Enugu East']
Length: 7, dtype: str

In [358]:
doctors.isnull().sum()

doctor_id      0
doctor_name    0
specialty      0
branch         0
dtype: int64

In [359]:
doctors.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   doctor_id    1500 non-null   str
 1   doctor_name  1500 non-null   str
 2   specialty    1500 non-null   str
 3   branch       1500 non-null   str
dtypes: str(4)
memory usage: 47.0 KB

#### Validate the cleaned Datasets. Perform Quality checks before loading them into the database

In [360]:
#patients.isnull().sum()
#appointments.isnull().sum()
#billing.isnull().sum()
doctors.isnull().sum()

doctor_id      0
doctor_name    0
specialty      0
branch         0
dtype: int64

In [361]:
# Check for duplicate Primary Keys in the datasets
#patients["patient_id"].duplicated().sum()

#appointments["appointment_id"].duplicated().sum()

#billing["invoice_id"].duplicated().sum()

doctors["doctor_id"].duplicated().sum()

np.int64(0)

In [362]:
# Verify the Data Types of the datasets 
patients.info()
appointments.info()
billing.info()
doctors.info()

<class 'pandas.DataFrame'>
Index: 1600 entries, 0 to 1669
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         1600 non-null   str
 1   full_name          1600 non-null   str
 2   gender             1600 non-null   str
 3   age                1600 non-null   int64
 4   phone_number       1600 non-null   str
 5   email              1600 non-null   str
 6   city               1600 non-null   str
 7   registration_date  1600 non-null   object
 8   age_group          1600 non-null   category
dtypes: category(1), int64(1), object(1), str(6)
memory usage: 178.8+ KB
<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   appointment_id      1800 non-null   str
 1   patient_id          1800 non-null   str
 2   doctor_id           1800 non-null   str
 3   appointment_date    1800 non-null   str
 4   appointment_status  1800 non-null   str
 5   reason_for_visit    1800 non-null   str
dtypes: str(6)
memory usage: 84.5 KB
<class 'pandas.DataFrame'>
Index: 1679 entries, 0 to 1699
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      1679 non-null   str
 1   patient_id      1679 non-null   str
 2   invoice_date    1679 non-null   str
 3   amount_charged  1679 non-null   int64
 4   amount_paid     1679 non-null   int64
 5   payment_method  1679 non-null   str
 6   payment_status  1679 non-null   str
dtypes: int64(2), str(5)
memory usage: 104.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   doctor_id    1500 non-null   str
 1   doctor_name  1500 non-null   str
 2   specialty    1500 non-null   str
 3   branch       1500 non-null   str
dtypes: str(4)
memory usage: 47.0 KB

#### Export the cleaned dataframes into data/cleaned_data

In [363]:
# patients cleaned_data
patients.to_csv("../data/cleaned_data/patients_cleaned.csv", index=False) # Save cleaned patients data. The index=False argument is used to prevent the index column from being saved in the CSV file. This is because the index column is not part of the original dataset and is not needed for analysis. By setting index=False, we ensure that only the relevant columns are saved in the cleaned data file.

In [364]:
# Appointments cleaned_data
appointments.to_csv("../data/cleaned_data/appointments_cleaned.csv", index=False) # Save cleaned appointments data. The index=False argument is used to prevent the index column from being saved in the CSV file. This is because the index column is not part of the original dataset and is not needed for analysis. By setting index=False, we ensure that only the relevant columns are saved in the cleaned data file.

In [365]:
# Billing cleaned_data 
billing.to_csv("../data/cleaned_data/billing_cleaned.csv", index=False) # Save cleaned billing data. The index=False argument is used to prevent the index column from being saved in the CSV file. This is because the index column is not part of the original dataset and is not needed for analysis. By setting index=False, we ensure that only the relevant columns are saved in the cleaned data file.

In [366]:
# Doctors cleaned_data
doctors.to_csv("../data/cleaned_data/doctors_cleaned.csv", index=False) # Save cleaned doctors data. The index=False argument is used to prevent the index column from being saved in the CSV file. This is because the index column is not part of the original dataset and is not needed for analysis. By setting index=False, we ensure that only the relevant columns are saved in the cleaned data file.

In [367]:
# Verify that the cleaned data files have been saved successfully
import os # This imports the os module, which provides a way to interact with the operating system. In this case, it is used to list the files in the specified directory.

os.listdir("../data/cleaned_data") # This line of code lists all the files in the specified directory ("../data/cleaned_data"). It helps to verify that the cleaned data files have been saved successfully by displaying their names in the output.

['appointments_cleaned.csv',
 'billing_cleaned.csv',
 'doctors_cleaned.csv',
 'patients_cleaned.csv']

In [368]:
# To Read the cleaned_data 
patients_cleaned = pd.read_csv("../data/cleaned_data/patients_cleaned.csv")
appointments_cleaned = pd.read_csv("../data/cleaned_data/appointments_cleaned.csv")
billing_cleaned = pd.read_csv("../data/cleaned_data/billing_cleaned.csv")
doctors_cleaned = pd.read_csv("../data/cleaned_data/doctors_cleaned.csv")

#### Loading the cleaned_data in Postgre

In [369]:
import sys
print(sys.executable)

c:\Documents\Desktop\Healthplus_Hospital_Data_Modernization_project\venv\Scripts\python.exe

In [378]:
import psycopg2
import sqlalchemy

print("Database packages are working")

Database packages are working

In [385]:
# Creating the engine to connect to the PostgreSQL database using SQLAlchemy. The connection string specifies the database type (postgresql), username (postgres), password (your_password), host (localhost), port (5432), and database name (healthplus_db). This engine will be used to interact with the database, allowing us to read from and write to it using pandas DataFrames.
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:goodlife20@localhost:5432/healthplus_modernization_db"
)

#### Load the cleaned_data

In [372]:
pateients_cleaned = pd.read_csv("../data/cleaned_data/patients_cleaned.csv")

In [373]:
appointments_cleaned = pd.read_csv("../data/cleaned_data/appointments_cleaned.csv")

In [374]:
billing_cleaned = pd.read_csv("../data/cleaned_data/billing_cleaned.csv")

In [375]:
doctors_cleaned = pd.read_csv("../data/cleaned_data/doctors_cleaned.csv")

#### Send the clean data to Postgres